# Generated by Django 5.0.4 on 2024-04-13 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tickets', '0004_alter_ticket_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='store_address',
            new_name='area',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='price',
        ),
        migrations.AddField(
            model_name='ticket',
            name='description',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='ticket',
            name='district',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='ticket',
            name='gramms',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
        ),
        migrations.AddField(
            model_name='ticket',
            name='price_for_kg',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=7),
        ),
        migrations.AddField(
            model_name='ticket',
            name='price_rost',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=7),
        ),
        migrations.AddField(
            model_name='ticket',
            name='price_tag',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=7),
        ),
    ]
