# Generated by Django 5.0.4 on 2024-04-13 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tickets', '0005_rename_store_address_ticket_area_remove_ticket_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='gramms',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
