# Generated by Django 5.0.4 on 2024-04-13 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tickets', '0007_alter_ticket_price_rost'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='category',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
