# Generated by Django 5.0.4 on 2024-04-14 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tickets', '0008_ticket_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=200)),
                ('district', models.CharField(default=None, max_length=200)),
                ('area', models.CharField(max_length=200)),
                ('product_name', models.CharField(max_length=100)),
                ('category', models.CharField(default=None, max_length=100)),
                ('price_tag', models.DecimalField(decimal_places=2, default=None, max_digits=7)),
                ('gramms', models.CharField(default=None, max_length=100)),
                ('price_for_kg', models.DecimalField(decimal_places=2, default=None, max_digits=7)),
                ('price_rost', models.CharField(default=None, max_length=200)),
            ],
        ),
    ]
